config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get "/about" => "pages#about"
  resources :posts
  resources :blogs
  resources :videos
  resources :contacts

end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :title, presence: true
    validates :body, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_attached_file :avatar, :styles => {
    :medium => { :geometry => "640x480", :format => 'flv' },
    :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }
  }, :processors => [:transcoder]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    
    def index
        @blogs = Blog.all.order('created_at DESC')
    end
    
    def show
        @blog =Blog.find(params[:id])
    end
    
    def new
        @blog = Blog.new
    end
    
    def create
        @blog=Blog.new(blog_params)
        
        # If post params do not meet secifications, do render instead of redirect b/c redirect refreshes input fields
        if @blog.save
            redirect_to @blog
        else
            render 'new'
        end
    end
    
    def edit
        @blog = Blog.find(params[:id])    
    end
    
    def update
        @blog = Blog.find(params[:id])  
        if @blog.update(params[:blog].permit(:tile, :body))
            redirect_to @blog
        else
            render 'edit'
        end
    end
    
    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        
        redirect_to blogs_path    
    end
    
    
    private
    def  blog_params
        params.require(:blog).permit(:title, :body)
    end
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
      @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to new_contact_path, notice: "Message sent."
    else
      redirect_to new_contact_path, notice: "Error occured."
    end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home 
    end
    
    def about
    end
    
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    before_filter :find_params, only: [:create, :update, :show, :delete]
    
    def index
       @videos = Video.all 
    end
    
    def create
        @video = Video.new(video_params)
    end
    
    def update
    end
    
    def delete
        @post.destroy
        
        redirect_to posts_path
    end
    
    def new
    end
    
    def show 
    end
        
    def edit
        if @video.update(params[:video].permit(:title, :description))
            redirect_to @video
        else
            render 'edit'
        end
    end
    
    def find_params
        @video = Video.find(params[:id])
    end
    
    private
    def video_params
       params.require(:video).permit(:title, :description) 
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
    
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
    
    <p><%= f.label :body %></p>
    <p><%= f.text_area :body %></p>
    
    <p><%= f.submit %></p>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<head>
    
</head>
<body>
  <div class="blog">
    
    <div class="jumbotron blog-jumbotron">
      <div class="container">
        <br><br><br><h4 class="text-center">Cunning, Inteeligent, Wise.</h4>
        <h1 class="text-center">Joshua's Blog</h1>
      </div>
    </div>
    <br><br>


  <div class="row-fluid">
    <% @blogs.each do |blog| %>
    <div class="col-xs-4">
      <div class="icon">
        <div class="thumbnail">
        <img src="https://images.unsplash.com/photo-1440470177828-6381dc5074ba?ixlib=rb-0.3.5&q=80&fm=jpg&s=6faf705d60f9804d03079755fb323a9a"></img>
        </div>
        <div class="caption">
        <h2><%= link_to blog.title, blog%></h2>
        <p class="date"><%= blog.created_at.strftime("%B, %d, %Y") %></p>
        <p class="post-body"><%= truncate(blog.body, :length => 150)%></p>
        </div>
      </div>
    </div>
  </div>


<% end %>
</div><!-- END BLOG PAGE BODY DIV -->
</body>

app/views/blogs/new.html.erb
<%= form_for :blog, url: blogs_path do |f| %>
    
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
    
    <p><%= f.label :body %></p>
    <p><%= f.text_area :body %></p>
    
    <p><%= f.submit %></p>
<% end %>

app/views/blogs/show.html.erb
<div class="blog-post">
<h1 class="title">
    <%= @blog.title %>
</h1>

<p class="date">
    Artfully crafted <%= time_ago_in_words(@blog.created_at) %> ago
    | <%= link_to "Edit", edit_blog_path(@blog) %>
    | <%= link_to "Delete", blog_path(@blog), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<p class="body">
    <%= @blog.body %>
</p>
</div>

app/views/contacts/new.html.erb
<!DOCTYPE html>
<head>
    
</head>
<body class="contact-body">

    <div class="row">
      <br><br><br><br><br><br><br><div class="col-md-4 col-md-offset-7">
        
          <%= form_for @contact do |f| %>
            <div class="form-group">
              <%= f.label :name, class: 'quicksand' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <br>
            <div class="form-group">
              <%= f.label :email, class: 'quicksand' %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <br>
            <div class="form-group">
              <%= f.label :comments, class: 'quicksand' %>
         
              <%= f.text_area :comments, class: 'form-control comments-area' %>
             
            </div>
            <%= f.submit 'Send this to Josh', class: 'btn btn-primary submit-btn quicksand' %>
          <% end %>
        
      </div>
    </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  
      <%= yield %>
  
      <div class="button_container" id="toggle">
      <span class="top"></span>
      <span class="middle"></span>
      <span class="bottom"></span>
    </div>
    
    <div class="overlay" id="overlay">
      <nav class="overlay-menu">
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Portfolio', videos_path %></li>
          <li><%= link_to 'Blog', blogs_path %></li>
          <li><%= link_to 'Contact', new_contact_path %></li>
        </ul>
      </nav>
    </div>


 







<script src="jquery.js"></script>
<script src="jquery.boxloader.min.js"></script>
<script src="custom.js"></script>
</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="assets/stylesheets/pages.scss">
    
</head>
<body>
  <div class="about">

    
        <br><br><br><br><br><br>
     <h1 class="jumbotron-title">About Joshua</h1>
     <br><br><br><br><br>
    <p class="about-body-text">Lorem ipsum dolor sit amet, eu sit enim debitis accusata, 
    ei nec dico errem dictas. In pro tollit assentior. 
    Brunch leggings salvia, cred bicycle rights craft beer sartorial. Taxidermy occupy Godard synth scenester DIY selfies, roof party food truck umami XOXO 
    wolf wayfarers Etsy trust fund. Squid whatever gentrify, 
    swag bicycle rights listicle leggings hoodie 90's disrupt cardigan Truffaut Austin direct trade. Cornhole art party vinyl cold-pressed tote bag. Odd Future freegan Echo Park kale chips artisan, umami Etsy 
    fixie cliche listicle Thundercats. Semiotics scenester locavore irony stumptown, brunch mlkshk Carles chambray butcher mustache freegan tilde taxidermy Thundercats. Synth selvage hella chia banjo tofu sriracha, 
    food truck banh mi 90's Truffaut whatever meditation pop-up.</p>
    <p class="about-body-text">
    Vinyl literally Carles umami banh mi church-key, meh PBR wayfarers narwhal Truffaut before they sold out vegan YOLO. 
    Paleo cred tote bag American Apparel, YOLO mumblecore ennui DIY pop-up kale chips banh mi. Odd Future art party +1, 
    whatever pour-over messenger bag cliche. Meh church-key crucifix 8-bit, organic tofu retro butcher yr jean shorts 
    mustache try-hard. Chambray fanny pack cold-pressed fashion axe, wolf wayfarers letterpress occupy paleo cray quinoa 
    seitan DIY meh. Single-origin coffee sartorial skateboard fanny pack fingerstache church-key. Roof party artisan plaid, lumbersexual 
    Brooklyn mixtape shabby chic fap vinyl kitsch irony sustainable Neutra.</p>
    <p class="about-body-text">
    Raw denim skateboard put a bird on it distillery tousled. Tote bag Brooklyn fixie, semiotics health goth aesthetic 
    skateboard. Vinyl paleo locavore Wes Anderson. Fixie twee pork belly, beard food truck Pitchfork blog biodiesel. 
    Letterpress seitan ethical Blue Bottle, sriracha forage hella gentrify PBR cliche. Paleo Echo Park pork belly 
    wayfarers, 3 wolf moon taxidermy polaroid slow-carb post-ironic Schlitz roof party High Life swag. Synth skateboard 
    Odd Future before they sold out, pickled chia biodiesel pour-over tattooed fixie.</p>
</div> <!-- END ABOUT PAGE BODY DIV -->  
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
</head>
<body>

    <div class="jumbotron header-container">
        <div class="video-container">
   
        </div><!--END VIDEO CONTAINER-->
        <br><br><br><br><h1 class="jumbotron-title">
           <img class="panda-logo"src="http://res.cloudinary.com/lptbt4ovx/image/upload/v1448346216/IMG_3466-1_bc64jj.jpg">
        <h1 class="birdman">
        </h1>
    </div><!--END HEADER CONTAINER-->
</body>
</html>

app/views/posts/new.html.erb
<%= form_for :blog, url: blogs_path do |f| %>
    
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>
    
    <p><%= f.label :body %></p>
    <p><%= f.text_area :body %></p>
    
    <p><%= f.submit %></p>
<% end %>

app/views/videos/index.html.erb
<!DOCTYPE html>

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">  

</head>
<body>
   
<!-- END NAVIGATION -->
    
    <div class="jumbotron portfolio-jumbotron text-center">
        <div class="container">
            <br><br><br>
            <h1 class="quicksand">Joshua's Videos</h1>
            <br><p class="quicksand">Joshua makes beautiful videos, and also news commercials.</p>
        </div>
    </div> 
    
    <% @videos.each do |video| %>
    <div class="row">
        <div class="col-xs-6 col-md-3">
        <p><%= video.title %></p>
        <p><%= video.description %></p>
        </div>
    </div>
    <% end %>   
    
</body>
</html>